project:
  type: website
  output-dir: docs

website:
  title: "lissyuse"
  navbar:
    left:
      - href: lissyuse.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

